### ISSUE TITLE
Connection to Nyxt hangs

### ISSUE THREAD

**Issue by JuanPabloMF** [ag91/emacs-with-nyxt#3]
Hi,

When I run `emacs-with-nyxt-start-and-connect-to-nyxt` Nyxt opens ok but my prompt gets blocked with the following message:

"Setting sly package to NYXT-USER"

If I `C-g` to stop the process I can see the following error:

```
The value
  NIL
is not of type
  SLYNK::CONNECTION
   [Condition of type TYPE-ERROR]
```
My config currently includes the following:

```
(use-package emacs-with-nyxt
  :ensure nil
  :load-path "~/.emacs.d/site-lisp/emacs-with-nyxt"
  )

(use-package sly
  :config
  (setq sly-lisp-implementations '((sbcl ("/usr/bin/sbcl"))))
)
```
I modified just two lines in emacs-with-nyxt.el to require sly and also open nyxt with swank:

```
;;(require 'slime)
(require 'org)
(require 's)
(require 'sly)
;; Many lines further...
(async-shell-command (format "nyxt -e \"(nyxt-user::start-swank)\""
```

And added auto-config.lisp to ~/.config/nyxt/.

**Comment by JuanPabloMF** [comment]
With Slime its working fine, but sly seems to be causing the problem.

**Comment by ag91** [comment]
Hey thanks for trying out this little script!
The problem should be that slime and sly uses two different backends. So Slime requires Swank as a server, while Sly (which was meant to be an improvement over Slime) requires Slynk.
This is why I provide https://github.com/ag91/emacs-with-nyxt/blob/master/auto-config.lisp#L38 in the Nyxt configuration in the repo. It will start Slynk for you (and you will not need to start Swank at all).
Could you try to include from ln 36 onwards in your Nyxt config and let me know if that solves your issue?
